//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChoiceCenium
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ChoiceCenium_dbEntities : DbContext
    {
        public ChoiceCenium_dbEntities()
            : base("name=ChoiceCenium_dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<KjedeInfoes> KjedeInfoes { get; set; }
        public virtual DbSet<Hotelinfoes> Hotelinfoes { get; set; }
    }
}
